name: C/C++ CI

on: [push]

jobs:
  build:
  name: C/C++
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: make Debug
      run:  make Debug -C Department_store_management_system/3_Implementation/
